version: '3.8'

services:
#paguina web
  web:
    build: .
    container_name: web
    ports:
      - "80:80"
#base de datos
  db:
    image: mysql:latest
    container_name: bbdd
    ports:
      - "3306:3306"
#adminer
  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8081:8080"


