version: '3.8'

services:
#paguina web
  web:
    build: .
    container_name: web
    ports:
      - 81:80
#base de datos
  db:
    image: mysql:latest
    container_name: bbdd
    ports:
      - 3307:3306
#adminer
  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080

